baseurl = "http://vjeantet.fr/"
copyright = "Turning Point Church"
disqusshortname = "vjeantet"
languagecode = "fr-FR"
paginate = 5
pluralizelisttitles = false
theme = "hugo-theme-casper"
title = "Turning Point Church"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120


[params]
author = "Tim Hunter"
authorlocation = "Rockville,Maryland"
authorwebsite = "http://vjeantet.fr"
authorbio = "Pastor of Turning Point Church of Rockville."
cover = "images/cover_polenord.jpg"
description = ""
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = ""
customFooterPartial = "netlify.html"

[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
