baseurl = "https://turningpointrockville.org/"
copyright = "Turning Point Church"
disqusshortname = "vjeantet"
languagecode = "en-EN"
paginate = 1
pluralizelisttitles = false
theme = "hugo-theme-casper"
title = "Turning Point Church"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[main.menu]]
identifier = "events"
name = "Events"
url="/"
weight = 100
[[menu.main]]
name = "Gallery"
pre = "<h3>Follow Us</h3>"
url = ""
weight = 100
[[menu.main]]
name = "Follow us on Social Media"
url = ""
weight = 101
[[menu.main]]
name = "Gallery"
pre = "<h3>Meet The Family</h3>"
url = "https://turningpointrockville.org/gallery/"
weight = 109



[params]
author = "Tim Hunter"
authorlocation = "Rockville,Maryland"
authorwebsite = "https://turningpointrockville.org"
authorbio = "Pastor of Turning Point Church of Rockville."
cover = "images/interior.jpg"
description = ""
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "images/logo.jpg"
twitterName = ""
customFooterPartial = "netlify.html"

[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
